title: SMTCoq
description: Communication between Coq and SAT/SMT solvers
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions

github:
  repository_url: https://github.com/smtcoq/smtcoq
